/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppWorkersRouteImport } from './routes/_app.workers'
import { Route as AppSettingsRouteImport } from './routes/_app.settings'
import { Route as AppPortalRouteImport } from './routes/_app.portal'
import { Route as AppDashboardRouteImport } from './routes/_app.dashboard'
import { Route as AppCoachRouteImport } from './routes/_app.coach'
import { Route as AppAuditRouteImport } from './routes/_app.audit'
import { Route as AppAlertsRouteImport } from './routes/_app.alerts'
import { Route as AppWorkersIndexRouteImport } from './routes/_app.workers.index'
import { Route as AppWorkersIdRouteImport } from './routes/_app.workers.$id'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppWorkersRoute = AppWorkersRouteImport.update({
  id: '/workers',
  path: '/workers',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppPortalRoute = AppPortalRouteImport.update({
  id: '/portal',
  path: '/portal',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppCoachRoute = AppCoachRouteImport.update({
  id: '/coach',
  path: '/coach',
  getParentRoute: () => AppRoute,
} as any)
const AppAuditRoute = AppAuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => AppRoute,
} as any)
const AppAlertsRoute = AppAlertsRouteImport.update({
  id: '/alerts',
  path: '/alerts',
  getParentRoute: () => AppRoute,
} as any)
const AppWorkersIndexRoute = AppWorkersIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppWorkersRoute,
} as any)
const AppWorkersIdRoute = AppWorkersIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AppWorkersRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/alerts': typeof AppAlertsRoute
  '/audit': typeof AppAuditRoute
  '/coach': typeof AppCoachRoute
  '/dashboard': typeof AppDashboardRoute
  '/portal': typeof AppPortalRoute
  '/settings': typeof AppSettingsRoute
  '/workers': typeof AppWorkersRouteWithChildren
  '/workers/$id': typeof AppWorkersIdRoute
  '/workers/': typeof AppWorkersIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/alerts': typeof AppAlertsRoute
  '/audit': typeof AppAuditRoute
  '/coach': typeof AppCoachRoute
  '/dashboard': typeof AppDashboardRoute
  '/portal': typeof AppPortalRoute
  '/settings': typeof AppSettingsRoute
  '/workers/$id': typeof AppWorkersIdRoute
  '/workers': typeof AppWorkersIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/_app/alerts': typeof AppAlertsRoute
  '/_app/audit': typeof AppAuditRoute
  '/_app/coach': typeof AppCoachRoute
  '/_app/dashboard': typeof AppDashboardRoute
  '/_app/portal': typeof AppPortalRoute
  '/_app/settings': typeof AppSettingsRoute
  '/_app/workers': typeof AppWorkersRouteWithChildren
  '/_app/workers/$id': typeof AppWorkersIdRoute
  '/_app/workers/': typeof AppWorkersIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/contact'
    | '/login'
    | '/signup'
    | '/alerts'
    | '/audit'
    | '/coach'
    | '/dashboard'
    | '/portal'
    | '/settings'
    | '/workers'
    | '/workers/$id'
    | '/workers/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/contact'
    | '/login'
    | '/signup'
    | '/alerts'
    | '/audit'
    | '/coach'
    | '/dashboard'
    | '/portal'
    | '/settings'
    | '/workers/$id'
    | '/workers'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/about'
    | '/contact'
    | '/login'
    | '/signup'
    | '/_app/alerts'
    | '/_app/audit'
    | '/_app/coach'
    | '/_app/dashboard'
    | '/_app/portal'
    | '/_app/settings'
    | '/_app/workers'
    | '/_app/workers/$id'
    | '/_app/workers/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  AboutRoute: typeof AboutRoute
  ContactRoute: typeof ContactRoute
  LoginRoute: typeof LoginRoute
  SignupRoute: typeof SignupRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/workers': {
      id: '/_app/workers'
      path: '/workers'
      fullPath: '/workers'
      preLoaderRoute: typeof AppWorkersRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings': {
      id: '/_app/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/portal': {
      id: '/_app/portal'
      path: '/portal'
      fullPath: '/portal'
      preLoaderRoute: typeof AppPortalRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dashboard': {
      id: '/_app/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/coach': {
      id: '/_app/coach'
      path: '/coach'
      fullPath: '/coach'
      preLoaderRoute: typeof AppCoachRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/audit': {
      id: '/_app/audit'
      path: '/audit'
      fullPath: '/audit'
      preLoaderRoute: typeof AppAuditRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/alerts': {
      id: '/_app/alerts'
      path: '/alerts'
      fullPath: '/alerts'
      preLoaderRoute: typeof AppAlertsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/workers/': {
      id: '/_app/workers/'
      path: '/'
      fullPath: '/workers/'
      preLoaderRoute: typeof AppWorkersIndexRouteImport
      parentRoute: typeof AppWorkersRoute
    }
    '/_app/workers/$id': {
      id: '/_app/workers/$id'
      path: '/$id'
      fullPath: '/workers/$id'
      preLoaderRoute: typeof AppWorkersIdRouteImport
      parentRoute: typeof AppWorkersRoute
    }
  }
}

interface AppWorkersRouteChildren {
  AppWorkersIdRoute: typeof AppWorkersIdRoute
  AppWorkersIndexRoute: typeof AppWorkersIndexRoute
}

const AppWorkersRouteChildren: AppWorkersRouteChildren = {
  AppWorkersIdRoute: AppWorkersIdRoute,
  AppWorkersIndexRoute: AppWorkersIndexRoute,
}

const AppWorkersRouteWithChildren = AppWorkersRoute._addFileChildren(
  AppWorkersRouteChildren,
)

interface AppRouteChildren {
  AppAlertsRoute: typeof AppAlertsRoute
  AppAuditRoute: typeof AppAuditRoute
  AppCoachRoute: typeof AppCoachRoute
  AppDashboardRoute: typeof AppDashboardRoute
  AppPortalRoute: typeof AppPortalRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppWorkersRoute: typeof AppWorkersRouteWithChildren
}

const AppRouteChildren: AppRouteChildren = {
  AppAlertsRoute: AppAlertsRoute,
  AppAuditRoute: AppAuditRoute,
  AppCoachRoute: AppCoachRoute,
  AppDashboardRoute: AppDashboardRoute,
  AppPortalRoute: AppPortalRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppWorkersRoute: AppWorkersRouteWithChildren,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  AboutRoute: AboutRoute,
  ContactRoute: ContactRoute,
  LoginRoute: LoginRoute,
  SignupRoute: SignupRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
